/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOrgsRouteImport } from './routes/_authenticated/orgs'
import { Route as AuthenticatedOOrgIdRouteImport } from './routes/_authenticated/o.$orgId'
import { Route as AuthenticatedOOrgIdIndexRouteImport } from './routes/_authenticated/o.$orgId.index'
import { Route as AuthenticatedOOrgIdAgreementsRouteImport } from './routes/_authenticated/o.$orgId.agreements'
import { Route as AuthenticatedOOrgIdEvidenceRouteImport } from './routes/_authenticated/o.$orgId.evidence'
import { Route as AuthenticatedOOrgIdObligationsRouteImport } from './routes/_authenticated/o.$orgId.obligations'
import { Route as AuthenticatedOOrgIdSettingsRouteImport } from './routes/_authenticated/o.$orgId.settings'
import { Route as AuthenticatedOOrgIdTasksRouteImport } from './routes/_authenticated/o.$orgId.tasks'
import { Route as AuthenticatedOOrgIdWorkflowsRouteImport } from './routes/_authenticated/o.$orgId.workflows'
import { Route as ApiPublicV1AgreementsRouteImport } from './routes/api/public/v1/agreements'
import { Route as AuthenticatedOOrgIdAgreementsIndexRouteImport } from './routes/_authenticated/o.$orgId.agreements.index'
import { Route as AuthenticatedOOrgIdAgreementsIdRouteImport } from './routes/_authenticated/o.$orgId.agreements.$id'
import { Route as AuthenticatedOOrgIdObligationsIndexRouteImport } from './routes/_authenticated/o.$orgId.obligations.index'
import { Route as AuthenticatedOOrgIdObligationsIdRouteImport } from './routes/_authenticated/o.$orgId.obligations.$id'
import { Route as ApiPublicV1AgreementsIdRouteImport } from './routes/api/public/v1/agreements.$id'
import { Route as ApiPublicV1ModuleHealthRouteImport } from './routes/api/public/v1/module.health'
import { Route as ApiPublicV1ModuleInfoRouteImport } from './routes/api/public/v1/module.info'
import { Route as ApiPublicV1ModuleOrganizationRouteImport } from './routes/api/public/v1/module.organization'
import { Route as ApiPublicV1ModuleWidgetsRouteImport } from './routes/api/public/v1/module.widgets'
import { Route as ApiPublicV1ModuleOrganizationOrgIdRouteImport } from './routes/api/public/v1/module.organization.$orgId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsRoute = AuthenticatedOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOOrgIdRoute = AuthenticatedOOrgIdRouteImport.update({
  id: '/o/$orgId',
  path: '/o/$orgId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOOrgIdIndexRoute =
  AuthenticatedOOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOOrgIdRoute,
  } as any)
const AuthenticatedOOrgIdAgreementsRoute =
  AuthenticatedOOrgIdAgreementsRouteImport.update({
    id: '/agreements',
    path: '/agreements',
    getParentRoute: () => AuthenticatedOOrgIdRoute,
  } as any)
const AuthenticatedOOrgIdEvidenceRoute =
  AuthenticatedOOrgIdEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => AuthenticatedOOrgIdRoute,
  } as any)
const AuthenticatedOOrgIdObligationsRoute =
  AuthenticatedOOrgIdObligationsRouteImport.update({
    id: '/obligations',
    path: '/obligations',
    getParentRoute: () => AuthenticatedOOrgIdRoute,
  } as any)
const AuthenticatedOOrgIdSettingsRoute =
  AuthenticatedOOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOOrgIdRoute,
  } as any)
const AuthenticatedOOrgIdTasksRoute =
  AuthenticatedOOrgIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedOOrgIdRoute,
  } as any)
const AuthenticatedOOrgIdWorkflowsRoute =
  AuthenticatedOOrgIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedOOrgIdRoute,
  } as any)
const ApiPublicV1AgreementsRoute = ApiPublicV1AgreementsRouteImport.update({
  id: '/api/public/v1/agreements',
  path: '/api/public/v1/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOOrgIdAgreementsIndexRoute =
  AuthenticatedOOrgIdAgreementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOOrgIdAgreementsRoute,
  } as any)
const AuthenticatedOOrgIdAgreementsIdRoute =
  AuthenticatedOOrgIdAgreementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOOrgIdAgreementsRoute,
  } as any)
const AuthenticatedOOrgIdObligationsIndexRoute =
  AuthenticatedOOrgIdObligationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOOrgIdObligationsRoute,
  } as any)
const AuthenticatedOOrgIdObligationsIdRoute =
  AuthenticatedOOrgIdObligationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOOrgIdObligationsRoute,
  } as any)
const ApiPublicV1AgreementsIdRoute = ApiPublicV1AgreementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1AgreementsRoute,
} as any)
const ApiPublicV1ModuleHealthRoute = ApiPublicV1ModuleHealthRouteImport.update({
  id: '/api/public/v1/module/health',
  path: '/api/public/v1/module/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ModuleInfoRoute = ApiPublicV1ModuleInfoRouteImport.update({
  id: '/api/public/v1/module/info',
  path: '/api/public/v1/module/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ModuleOrganizationRoute =
  ApiPublicV1ModuleOrganizationRouteImport.update({
    id: '/api/public/v1/module/organization',
    path: '/api/public/v1/module/organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ModuleWidgetsRoute =
  ApiPublicV1ModuleWidgetsRouteImport.update({
    id: '/api/public/v1/module/widgets',
    path: '/api/public/v1/module/widgets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ModuleOrganizationOrgIdRoute =
  ApiPublicV1ModuleOrganizationOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => ApiPublicV1ModuleOrganizationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/orgs': typeof AuthenticatedOrgsRoute
  '/o/$orgId': typeof AuthenticatedOOrgIdRouteWithChildren
  '/o/$orgId/agreements': typeof AuthenticatedOOrgIdAgreementsRouteWithChildren
  '/o/$orgId/evidence': typeof AuthenticatedOOrgIdEvidenceRoute
  '/o/$orgId/obligations': typeof AuthenticatedOOrgIdObligationsRouteWithChildren
  '/o/$orgId/settings': typeof AuthenticatedOOrgIdSettingsRoute
  '/o/$orgId/tasks': typeof AuthenticatedOOrgIdTasksRoute
  '/o/$orgId/workflows': typeof AuthenticatedOOrgIdWorkflowsRoute
  '/api/public/v1/agreements': typeof ApiPublicV1AgreementsRouteWithChildren
  '/o/$orgId/': typeof AuthenticatedOOrgIdIndexRoute
  '/o/$orgId/agreements/$id': typeof AuthenticatedOOrgIdAgreementsIdRoute
  '/o/$orgId/obligations/$id': typeof AuthenticatedOOrgIdObligationsIdRoute
  '/api/public/v1/agreements/$id': typeof ApiPublicV1AgreementsIdRoute
  '/api/public/v1/module/health': typeof ApiPublicV1ModuleHealthRoute
  '/api/public/v1/module/info': typeof ApiPublicV1ModuleInfoRoute
  '/api/public/v1/module/organization': typeof ApiPublicV1ModuleOrganizationRouteWithChildren
  '/api/public/v1/module/widgets': typeof ApiPublicV1ModuleWidgetsRoute
  '/o/$orgId/agreements/': typeof AuthenticatedOOrgIdAgreementsIndexRoute
  '/o/$orgId/obligations/': typeof AuthenticatedOOrgIdObligationsIndexRoute
  '/api/public/v1/module/organization/$orgId': typeof ApiPublicV1ModuleOrganizationOrgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/orgs': typeof AuthenticatedOrgsRoute
  '/o/$orgId/evidence': typeof AuthenticatedOOrgIdEvidenceRoute
  '/o/$orgId/settings': typeof AuthenticatedOOrgIdSettingsRoute
  '/o/$orgId/tasks': typeof AuthenticatedOOrgIdTasksRoute
  '/o/$orgId/workflows': typeof AuthenticatedOOrgIdWorkflowsRoute
  '/api/public/v1/agreements': typeof ApiPublicV1AgreementsRouteWithChildren
  '/o/$orgId': typeof AuthenticatedOOrgIdIndexRoute
  '/o/$orgId/agreements/$id': typeof AuthenticatedOOrgIdAgreementsIdRoute
  '/o/$orgId/obligations/$id': typeof AuthenticatedOOrgIdObligationsIdRoute
  '/api/public/v1/agreements/$id': typeof ApiPublicV1AgreementsIdRoute
  '/api/public/v1/module/health': typeof ApiPublicV1ModuleHealthRoute
  '/api/public/v1/module/info': typeof ApiPublicV1ModuleInfoRoute
  '/api/public/v1/module/organization': typeof ApiPublicV1ModuleOrganizationRouteWithChildren
  '/api/public/v1/module/widgets': typeof ApiPublicV1ModuleWidgetsRoute
  '/o/$orgId/agreements': typeof AuthenticatedOOrgIdAgreementsIndexRoute
  '/o/$orgId/obligations': typeof AuthenticatedOOrgIdObligationsIndexRoute
  '/api/public/v1/module/organization/$orgId': typeof ApiPublicV1ModuleOrganizationOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/orgs': typeof AuthenticatedOrgsRoute
  '/_authenticated/o/$orgId': typeof AuthenticatedOOrgIdRouteWithChildren
  '/_authenticated/o/$orgId/agreements': typeof AuthenticatedOOrgIdAgreementsRouteWithChildren
  '/_authenticated/o/$orgId/evidence': typeof AuthenticatedOOrgIdEvidenceRoute
  '/_authenticated/o/$orgId/obligations': typeof AuthenticatedOOrgIdObligationsRouteWithChildren
  '/_authenticated/o/$orgId/settings': typeof AuthenticatedOOrgIdSettingsRoute
  '/_authenticated/o/$orgId/tasks': typeof AuthenticatedOOrgIdTasksRoute
  '/_authenticated/o/$orgId/workflows': typeof AuthenticatedOOrgIdWorkflowsRoute
  '/api/public/v1/agreements': typeof ApiPublicV1AgreementsRouteWithChildren
  '/_authenticated/o/$orgId/': typeof AuthenticatedOOrgIdIndexRoute
  '/_authenticated/o/$orgId/agreements/$id': typeof AuthenticatedOOrgIdAgreementsIdRoute
  '/_authenticated/o/$orgId/obligations/$id': typeof AuthenticatedOOrgIdObligationsIdRoute
  '/api/public/v1/agreements/$id': typeof ApiPublicV1AgreementsIdRoute
  '/api/public/v1/module/health': typeof ApiPublicV1ModuleHealthRoute
  '/api/public/v1/module/info': typeof ApiPublicV1ModuleInfoRoute
  '/api/public/v1/module/organization': typeof ApiPublicV1ModuleOrganizationRouteWithChildren
  '/api/public/v1/module/widgets': typeof ApiPublicV1ModuleWidgetsRoute
  '/_authenticated/o/$orgId/agreements/': typeof AuthenticatedOOrgIdAgreementsIndexRoute
  '/_authenticated/o/$orgId/obligations/': typeof AuthenticatedOOrgIdObligationsIndexRoute
  '/api/public/v1/module/organization/$orgId': typeof ApiPublicV1ModuleOrganizationOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/orgs'
    | '/o/$orgId'
    | '/o/$orgId/agreements'
    | '/o/$orgId/evidence'
    | '/o/$orgId/obligations'
    | '/o/$orgId/settings'
    | '/o/$orgId/tasks'
    | '/o/$orgId/workflows'
    | '/api/public/v1/agreements'
    | '/o/$orgId/'
    | '/o/$orgId/agreements/$id'
    | '/o/$orgId/obligations/$id'
    | '/api/public/v1/agreements/$id'
    | '/api/public/v1/module/health'
    | '/api/public/v1/module/info'
    | '/api/public/v1/module/organization'
    | '/api/public/v1/module/widgets'
    | '/o/$orgId/agreements/'
    | '/o/$orgId/obligations/'
    | '/api/public/v1/module/organization/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/orgs'
    | '/o/$orgId/evidence'
    | '/o/$orgId/settings'
    | '/o/$orgId/tasks'
    | '/o/$orgId/workflows'
    | '/api/public/v1/agreements'
    | '/o/$orgId'
    | '/o/$orgId/agreements/$id'
    | '/o/$orgId/obligations/$id'
    | '/api/public/v1/agreements/$id'
    | '/api/public/v1/module/health'
    | '/api/public/v1/module/info'
    | '/api/public/v1/module/organization'
    | '/api/public/v1/module/widgets'
    | '/o/$orgId/agreements'
    | '/o/$orgId/obligations'
    | '/api/public/v1/module/organization/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/orgs'
    | '/_authenticated/o/$orgId'
    | '/_authenticated/o/$orgId/agreements'
    | '/_authenticated/o/$orgId/evidence'
    | '/_authenticated/o/$orgId/obligations'
    | '/_authenticated/o/$orgId/settings'
    | '/_authenticated/o/$orgId/tasks'
    | '/_authenticated/o/$orgId/workflows'
    | '/api/public/v1/agreements'
    | '/_authenticated/o/$orgId/'
    | '/_authenticated/o/$orgId/agreements/$id'
    | '/_authenticated/o/$orgId/obligations/$id'
    | '/api/public/v1/agreements/$id'
    | '/api/public/v1/module/health'
    | '/api/public/v1/module/info'
    | '/api/public/v1/module/organization'
    | '/api/public/v1/module/widgets'
    | '/_authenticated/o/$orgId/agreements/'
    | '/_authenticated/o/$orgId/obligations/'
    | '/api/public/v1/module/organization/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicV1AgreementsRoute: typeof ApiPublicV1AgreementsRouteWithChildren
  ApiPublicV1ModuleHealthRoute: typeof ApiPublicV1ModuleHealthRoute
  ApiPublicV1ModuleInfoRoute: typeof ApiPublicV1ModuleInfoRoute
  ApiPublicV1ModuleOrganizationRoute: typeof ApiPublicV1ModuleOrganizationRouteWithChildren
  ApiPublicV1ModuleWidgetsRoute: typeof ApiPublicV1ModuleWidgetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs': {
      id: '/_authenticated/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AuthenticatedOrgsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/o/$orgId': {
      id: '/_authenticated/o/$orgId'
      path: '/o/$orgId'
      fullPath: '/o/$orgId'
      preLoaderRoute: typeof AuthenticatedOOrgIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/o/$orgId/': {
      id: '/_authenticated/o/$orgId/'
      path: '/'
      fullPath: '/o/$orgId/'
      preLoaderRoute: typeof AuthenticatedOOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgIdRoute
    }
    '/_authenticated/o/$orgId/agreements': {
      id: '/_authenticated/o/$orgId/agreements'
      path: '/agreements'
      fullPath: '/o/$orgId/agreements'
      preLoaderRoute: typeof AuthenticatedOOrgIdAgreementsRouteImport
      parentRoute: typeof AuthenticatedOOrgIdRoute
    }
    '/_authenticated/o/$orgId/evidence': {
      id: '/_authenticated/o/$orgId/evidence'
      path: '/evidence'
      fullPath: '/o/$orgId/evidence'
      preLoaderRoute: typeof AuthenticatedOOrgIdEvidenceRouteImport
      parentRoute: typeof AuthenticatedOOrgIdRoute
    }
    '/_authenticated/o/$orgId/obligations': {
      id: '/_authenticated/o/$orgId/obligations'
      path: '/obligations'
      fullPath: '/o/$orgId/obligations'
      preLoaderRoute: typeof AuthenticatedOOrgIdObligationsRouteImport
      parentRoute: typeof AuthenticatedOOrgIdRoute
    }
    '/_authenticated/o/$orgId/settings': {
      id: '/_authenticated/o/$orgId/settings'
      path: '/settings'
      fullPath: '/o/$orgId/settings'
      preLoaderRoute: typeof AuthenticatedOOrgIdSettingsRouteImport
      parentRoute: typeof AuthenticatedOOrgIdRoute
    }
    '/_authenticated/o/$orgId/tasks': {
      id: '/_authenticated/o/$orgId/tasks'
      path: '/tasks'
      fullPath: '/o/$orgId/tasks'
      preLoaderRoute: typeof AuthenticatedOOrgIdTasksRouteImport
      parentRoute: typeof AuthenticatedOOrgIdRoute
    }
    '/_authenticated/o/$orgId/workflows': {
      id: '/_authenticated/o/$orgId/workflows'
      path: '/workflows'
      fullPath: '/o/$orgId/workflows'
      preLoaderRoute: typeof AuthenticatedOOrgIdWorkflowsRouteImport
      parentRoute: typeof AuthenticatedOOrgIdRoute
    }
    '/api/public/v1/agreements': {
      id: '/api/public/v1/agreements'
      path: '/api/public/v1/agreements'
      fullPath: '/api/public/v1/agreements'
      preLoaderRoute: typeof ApiPublicV1AgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/o/$orgId/agreements/': {
      id: '/_authenticated/o/$orgId/agreements/'
      path: '/'
      fullPath: '/o/$orgId/agreements/'
      preLoaderRoute: typeof AuthenticatedOOrgIdAgreementsIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgIdAgreementsRoute
    }
    '/_authenticated/o/$orgId/agreements/$id': {
      id: '/_authenticated/o/$orgId/agreements/$id'
      path: '/$id'
      fullPath: '/o/$orgId/agreements/$id'
      preLoaderRoute: typeof AuthenticatedOOrgIdAgreementsIdRouteImport
      parentRoute: typeof AuthenticatedOOrgIdAgreementsRoute
    }
    '/_authenticated/o/$orgId/obligations/': {
      id: '/_authenticated/o/$orgId/obligations/'
      path: '/'
      fullPath: '/o/$orgId/obligations/'
      preLoaderRoute: typeof AuthenticatedOOrgIdObligationsIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgIdObligationsRoute
    }
    '/_authenticated/o/$orgId/obligations/$id': {
      id: '/_authenticated/o/$orgId/obligations/$id'
      path: '/$id'
      fullPath: '/o/$orgId/obligations/$id'
      preLoaderRoute: typeof AuthenticatedOOrgIdObligationsIdRouteImport
      parentRoute: typeof AuthenticatedOOrgIdObligationsRoute
    }
    '/api/public/v1/agreements/$id': {
      id: '/api/public/v1/agreements/$id'
      path: '/$id'
      fullPath: '/api/public/v1/agreements/$id'
      preLoaderRoute: typeof ApiPublicV1AgreementsIdRouteImport
      parentRoute: typeof ApiPublicV1AgreementsRoute
    }
    '/api/public/v1/module/health': {
      id: '/api/public/v1/module/health'
      path: '/api/public/v1/module/health'
      fullPath: '/api/public/v1/module/health'
      preLoaderRoute: typeof ApiPublicV1ModuleHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/module/info': {
      id: '/api/public/v1/module/info'
      path: '/api/public/v1/module/info'
      fullPath: '/api/public/v1/module/info'
      preLoaderRoute: typeof ApiPublicV1ModuleInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/module/organization': {
      id: '/api/public/v1/module/organization'
      path: '/api/public/v1/module/organization'
      fullPath: '/api/public/v1/module/organization'
      preLoaderRoute: typeof ApiPublicV1ModuleOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/module/widgets': {
      id: '/api/public/v1/module/widgets'
      path: '/api/public/v1/module/widgets'
      fullPath: '/api/public/v1/module/widgets'
      preLoaderRoute: typeof ApiPublicV1ModuleWidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/module/organization/$orgId': {
      id: '/api/public/v1/module/organization/$orgId'
      path: '/$orgId'
      fullPath: '/api/public/v1/module/organization/$orgId'
      preLoaderRoute: typeof ApiPublicV1ModuleOrganizationOrgIdRouteImport
      parentRoute: typeof ApiPublicV1ModuleOrganizationRoute
    }
  }
}

interface AuthenticatedOOrgIdAgreementsRouteChildren {
  AuthenticatedOOrgIdAgreementsIdRoute: typeof AuthenticatedOOrgIdAgreementsIdRoute
  AuthenticatedOOrgIdAgreementsIndexRoute: typeof AuthenticatedOOrgIdAgreementsIndexRoute
}

const AuthenticatedOOrgIdAgreementsRouteChildren: AuthenticatedOOrgIdAgreementsRouteChildren =
  {
    AuthenticatedOOrgIdAgreementsIdRoute: AuthenticatedOOrgIdAgreementsIdRoute,
    AuthenticatedOOrgIdAgreementsIndexRoute:
      AuthenticatedOOrgIdAgreementsIndexRoute,
  }

const AuthenticatedOOrgIdAgreementsRouteWithChildren =
  AuthenticatedOOrgIdAgreementsRoute._addFileChildren(
    AuthenticatedOOrgIdAgreementsRouteChildren,
  )

interface AuthenticatedOOrgIdObligationsRouteChildren {
  AuthenticatedOOrgIdObligationsIdRoute: typeof AuthenticatedOOrgIdObligationsIdRoute
  AuthenticatedOOrgIdObligationsIndexRoute: typeof AuthenticatedOOrgIdObligationsIndexRoute
}

const AuthenticatedOOrgIdObligationsRouteChildren: AuthenticatedOOrgIdObligationsRouteChildren =
  {
    AuthenticatedOOrgIdObligationsIdRoute:
      AuthenticatedOOrgIdObligationsIdRoute,
    AuthenticatedOOrgIdObligationsIndexRoute:
      AuthenticatedOOrgIdObligationsIndexRoute,
  }

const AuthenticatedOOrgIdObligationsRouteWithChildren =
  AuthenticatedOOrgIdObligationsRoute._addFileChildren(
    AuthenticatedOOrgIdObligationsRouteChildren,
  )

interface AuthenticatedOOrgIdRouteChildren {
  AuthenticatedOOrgIdAgreementsRoute: typeof AuthenticatedOOrgIdAgreementsRouteWithChildren
  AuthenticatedOOrgIdEvidenceRoute: typeof AuthenticatedOOrgIdEvidenceRoute
  AuthenticatedOOrgIdObligationsRoute: typeof AuthenticatedOOrgIdObligationsRouteWithChildren
  AuthenticatedOOrgIdSettingsRoute: typeof AuthenticatedOOrgIdSettingsRoute
  AuthenticatedOOrgIdTasksRoute: typeof AuthenticatedOOrgIdTasksRoute
  AuthenticatedOOrgIdWorkflowsRoute: typeof AuthenticatedOOrgIdWorkflowsRoute
  AuthenticatedOOrgIdIndexRoute: typeof AuthenticatedOOrgIdIndexRoute
}

const AuthenticatedOOrgIdRouteChildren: AuthenticatedOOrgIdRouteChildren = {
  AuthenticatedOOrgIdAgreementsRoute:
    AuthenticatedOOrgIdAgreementsRouteWithChildren,
  AuthenticatedOOrgIdEvidenceRoute: AuthenticatedOOrgIdEvidenceRoute,
  AuthenticatedOOrgIdObligationsRoute:
    AuthenticatedOOrgIdObligationsRouteWithChildren,
  AuthenticatedOOrgIdSettingsRoute: AuthenticatedOOrgIdSettingsRoute,
  AuthenticatedOOrgIdTasksRoute: AuthenticatedOOrgIdTasksRoute,
  AuthenticatedOOrgIdWorkflowsRoute: AuthenticatedOOrgIdWorkflowsRoute,
  AuthenticatedOOrgIdIndexRoute: AuthenticatedOOrgIdIndexRoute,
}

const AuthenticatedOOrgIdRouteWithChildren =
  AuthenticatedOOrgIdRoute._addFileChildren(AuthenticatedOOrgIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgsRoute: typeof AuthenticatedOrgsRoute
  AuthenticatedOOrgIdRoute: typeof AuthenticatedOOrgIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgsRoute: AuthenticatedOrgsRoute,
  AuthenticatedOOrgIdRoute: AuthenticatedOOrgIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1AgreementsRouteChildren {
  ApiPublicV1AgreementsIdRoute: typeof ApiPublicV1AgreementsIdRoute
}

const ApiPublicV1AgreementsRouteChildren: ApiPublicV1AgreementsRouteChildren = {
  ApiPublicV1AgreementsIdRoute: ApiPublicV1AgreementsIdRoute,
}

const ApiPublicV1AgreementsRouteWithChildren =
  ApiPublicV1AgreementsRoute._addFileChildren(
    ApiPublicV1AgreementsRouteChildren,
  )

interface ApiPublicV1ModuleOrganizationRouteChildren {
  ApiPublicV1ModuleOrganizationOrgIdRoute: typeof ApiPublicV1ModuleOrganizationOrgIdRoute
}

const ApiPublicV1ModuleOrganizationRouteChildren: ApiPublicV1ModuleOrganizationRouteChildren =
  {
    ApiPublicV1ModuleOrganizationOrgIdRoute:
      ApiPublicV1ModuleOrganizationOrgIdRoute,
  }

const ApiPublicV1ModuleOrganizationRouteWithChildren =
  ApiPublicV1ModuleOrganizationRoute._addFileChildren(
    ApiPublicV1ModuleOrganizationRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicV1AgreementsRoute: ApiPublicV1AgreementsRouteWithChildren,
  ApiPublicV1ModuleHealthRoute: ApiPublicV1ModuleHealthRoute,
  ApiPublicV1ModuleInfoRoute: ApiPublicV1ModuleInfoRoute,
  ApiPublicV1ModuleOrganizationRoute:
    ApiPublicV1ModuleOrganizationRouteWithChildren,
  ApiPublicV1ModuleWidgetsRoute: ApiPublicV1ModuleWidgetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
